### PR TITLE
Final Pull Request 12/4/2018

### PR DESCRIPTION
**Pull request by ghost**
(Put an `X` inside the `[ ]` to denote check mark `[X]`.)

- [ ] **If creating a new file :**
  - [ ] added links to it in the README files ?
  - [ ] included tests with it ?
  - [ ] added description (overview of algorithm, time and space compleixty, and possible edge case) in docstrings ?

- [ ] **if done some changes :**
  - [ ] wrote short description in the PR explaining what the changes do ?
  - [ ] Fixes #[issue number] if related to any issue

- [ ] **other**

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @cooljohnny3

**Comment by kyledewey** [comment]
Also assigned @michaelmunje

**Review by michaelmunje — APPROVED** [review]
Looks good for simple unit tests however this is very systematic behavior that can be a great candidate for randomized automated testing which should be relatively simple.

**Review by cooljohnny3 — APPROVED** [review]
The tests seem good but they only seem to test single cases.  Some of there could probably be turned into property tests.

**Pull request merged**
